baseurl = "https://progrhyme.github.io/fireap-doc"
languageCode = "en-us"
title = "fireap"
theme = "bootie-docs"
copyright = "Copyright (c) 2016-2017, IKEDA Kiyoshi; All rights reserved."

[params]
  description = "(fire + reap) Fast task runner on Consul cluster"
  #withSitePosts = true
  searchDomain = "progrhyme.github.io/fireap-doc"
  noCategoryLink = true
  repositoryUrl = "https://github.com/progrhyme/fireap/"
  highlightStyle = "atelier-forest-dark"

[[menu.main]]
  name = "Quickstart"
  url  = "/getting-started/"
  weight = 20

[[menu.main]]
  name = "CLI"
  url = "/cli-usage/"
  weight = 30

[[menu.main]]
  name = "Spec"
  url = "/specification/"
  weight = 40
